apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-deployment
  labels:
    app: service-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-deployment
  template:
    metadata:
      labels:
        app: service-deployment
    spec:
      containers:
      - name: service-deployment
        image: taktuk/test_week15:v0.8
        ports:
        - containerPort: 8000
        env:
        - name: MYSQL_HOST
          value: mysql-0.mysql
        - name: MYSQL_USER
          value: 'root'
        - name: MYSQL_PASSWORD
          value: 'rootpassword'
        - name: MYSQL_DATABASE
          value: 'classicmodels'